### ISSUE TITLE
requirements.txt broken

### ISSUE THREAD

**Issue by kbaegis** [dvdhpkns/swautocheckin#2]
> Downloading/unpacking wsgiref (from -r requirements.txt (line 14))
>  Downloading wsgiref-0.1.2.zip
>  Running setup.py (path:/tmp/pip-build-664mx38c/wsgiref/setup.py) egg_info for package wsgiref
>    Traceback (most recent call last):
>      File "<string>", line 17, in <module>
>      File "/tmp/pip-build-664mx38c/wsgiref/setup.py", line 5, in <module>
>        import ez_setup
>      File "/tmp/pip-build-664mx38c/wsgiref/ez_setup/**init**.py", line 170
>        print "Setuptools version",version,"or greater has been installed."
>                                 ^
>    SyntaxError: Missing parentheses in call to 'print'
>    Complete output from command python setup.py egg_info:
>    Traceback (most recent call last):
> 
>  File "<string>", line 17, in <module>
> 
>  File "/tmp/pip-build-664mx38c/wsgiref/setup.py", line 5, in <module>
> 
>    import ez_setup
> 
>  File "/tmp/pip-build-664mx38c/wsgiref/ez_setup/**init**.py", line 170
> 
>    print "Setuptools version",version,"or greater has been installed."
> 
> ```
>                         ^
> ```
> 
> SyntaxError: Missing parentheses in call to 'print'
> ---
> 
> Cleaning up...
> Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-664mx38c/wsgiref
> Storing debug log for failure in /home/ubuntu/.pip/pip.log

**Comment by dvdhpkns** [comment]
@kbaegis I just tried creating a new virtualenv and doing pip a pip install from the requirements file and it worked for me. Using python version 2.7.9.
